resolved issue#21
sanand0/xmljson pull request #22
Opened 2017-06-20 09:31 UTC by mukultaneja

2017-06-20 11:49 UTC, dagwieers requested changes
Please don't change anything except the needed changes. I do not agree with splitting lines. It does not make the code more readable, quite the opposite. So don't mix cosmetic changes (PEP8) with real modifications.

2017-06-26 06:22 UTC, sanand0 commented
Thanks @mukultaneja -- could you please introduce the test cases as discussed?

2017-06-26 12:28 UTC, mukultaneja commented
Hi Anand, I have added a test case in the existing test_data method for Abdera Convention.

2017-06-26 12:47 UTC, sanand0 commented
@mukultaneja - the Travis checks are failing. Could you please take a look?

@mattgd - this is a PR aimed at the issue #21 you'd raised. Thought I'd loop you in.

2017-06-26 21:55 UTC, mattgd commented
@sanand0 Thanks for the heads up and for fixing this issue. I appreciate it.

2017-06-27 19:21 UTC, mukultaneja commented
@mattgd thanks.

2017-07-02 11:05 UTC, mukultaneja commented
Hi @dagwieers,
I am looking into the issue that why Travis CI build is failing. After looking into the test report [https://travis-ci.org/sanand0/xmljson/jobs/247079647](https://travis-ci.org/sanand0/xmljson/jobs/247079647), I found that two existing test cases (1 for Abdera and 1 for Cobra) are failing, would you mind if I dig more into the code to resolve this build failing issue?

2017-07-02 18:19 UTC, dagwieers commented
@mukultaneja The tests were working fine before. [![Travis CI](https://img.shields.io/travis/sanand0/xmljson.svg)](https://travis-ci.org/sanand0/xmljson) They only started to fail with your commit, so I expect the failures to be caused by your changes. We will not accept your changes if it fails te Travis CI tests.

2017-07-02 18:51 UTC, mukultaneja commented
thanks, @dagwieers I am looking into change and update it so that Travis CI tests will pass.

2017-07-16 13:50 UTC, mukultaneja commented
Hi @all,

I have updated the code for my pull request so that it could pass all the test cases. I have added more nested test cases as well to validate my new changes.

I would request all of you to take a look at the changes and the test cases once. Please let me know if they are correct or need some modifications.

2017-07-17 10:36 UTC, dagwieers requested changes

2017-07-17 10:36 UTC, dagwieers commented on xmljson/__init__.py
>          count = Counter(child.tag for child in children)
If your code is correct, `count` here is also not needed.

2017-07-17 11:09 UTC, mukultaneja commented on xmljson/__init__.py
>          count = Counter(child.tag for child in children)
HI @dagwieers, thanks for the suggestion. I have removed the count variable and updated the code.

2017-07-17 12:20 UTC, dagwieers commented
I would like to get feedback from @sanand0 as he wrote the original code.

2017-07-17 16:27 UTC, sanand0 commented
I'm perfectly fine with this @dagwieers - this affects only the Abdera convention that you'd authored, so if you're OK with the test cases and the change, I'm perfectly happy to merge. It's a minimalist change, so that's great too.

Are the revised test cases in line with your expectation on the Abdera convention?

2017-08-01 08:40 UTC, merged